[package]
name = "gir-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = "0.3"
log = "0.4"
gir-parser = { git = "https://github.com/bilelmoussaoui/gir-parser" }
clap = { version = "4.5.6", features = ["derive"] }
once_cell = "1.19.0"
